### ISSUE TITLE
Welcome and Questions

### ISSUE THREAD

**Issue by asantacoloma24** [ufosc/albot-and-albota#10]
When a new user joins the discord, let the Bot send user a welcome message and inform them if they have any questions to use !question to notify officers.

**Comment by JING1201** [comment]
<img width="863" alt="screen shot 2018-09-05 at 22 26 42" src="https://user-images.githubusercontent.com/19191124/45131407-d3991c80-b15a-11e8-823f-0ffe8cfefe0d.png">
Anything you guys want to add to the message?

**Comment by hjarrell** [comment]
Partially finished with #11

**Comment by hjarrell** [comment]
Split this issue up into #18 and #19
