### ISSUE TITLE
Raise MissingPermissions upon permissions check errors

### ISSUE THREAD

**Issue by alexandershuping** [ufosc/albot-and-albota#14]
The check functions in util.py check whether the user who runs a given command has a certain role. Thus, failing these checks would fall under the `commands.errors.MissingPermissions` error type. However, when the functions return `False`, the discord.py library raises a generic `CheckError` instead. 

Raising a `MissingPermissions` error instead of returning `False` would allow for the bot to log and handle permissions errors more easily. This could be implemented with a few small changes to `util.py`.

**Comment by hjarrell** [comment]
This is fixed in 24ab7854ed8ca1771509474a17316346f39eadba which changes the util checks to the discord.py builtin checks for has_role and is_owner. They raise the correct exceptions.
