### ISSUE TITLE
Bots should mispell more 

### ISSUE THREAD

**Issue by xeranimus** [ufosc/albot-and-albota#29]
In order to feel more humans natural (so memebers feel more comfortable susing it ) the boat should emulate suman behavior. There for i propose that the bt should mimisspell words on purpose, sometimes. 

To maej this as ralistic as possible, you should build a statistical model for each keypress. Pressing an "e" might work 80% of the time, but 10% of the time it might result in a"w" o1% result in a 's', etc. Indels should also be considered here.

IN fact, to make it as aaccurate as possible, we should build a neural nework and base it off of the existing messages on the discord server.

Just my too sense.

**Comment by JING1201** [comment]
Can I make this my winter project hahaha
