### ISSUE TITLE
Update the cog classes for the rewrite

### ISSUE THREAD

**Issue by hjarrell** [ufosc/albot-and-albota#32]
The new rewrite version of Discord.py uses a Cog class that cogs should inherit from. We should update our dependency on discord.py and upgrade our cogs to this form. 

See: https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html

**Comment by swiftlee** [comment]
Created a pull-request. Check https://github.com/ufosc/albot-and-albota/pull/33

**Comment by swiftlee** [comment]
Created a second pull request in placement of the other: https://github.com/ufosc/albot-and-albota/pull/35

**Comment by hjarrell** [comment]
Closed by #35
