### ISSUE TITLE
Make the #getting-started channel generate using the bot

### ISSUE THREAD

**Issue by hjarrell** [ufosc/albot-and-albota#41]
The #gettingstarted channel should be formatted and generated by the bot. This could read from GitHub, files, database, club-backend, or admin direct commands. This should display all the different active projects and the resources on how to get started.

**Comment by logandgsmith** [comment]
To add onto this, we should probably move !projects to read from the database so that we can add and archive projects quicker.

**Comment by logandgsmith** [comment]
Come to think of it, we might want to move this to next semester's release so that we can cement the website backend as our single source of truth. I think I'm going to put this issue on ice for the time being.

**Comment by logandgsmith** [comment]
Closing this for now. Can re-open once we figure out the backend.
