### ISSUE TITLE
Club Seat Positions

### ISSUE THREAD

**Issue by swiftlee** [ufosc/albot-and-albota#44]
Add listings for club seat positions and allow for certain roles to reassign seats as elections pass. An idea would to be automatically integrate the elections with this and assign the seats automatically upon execution of a command.

Examples: (keep in mind that we can invent more intuitive aliases for commands)
?govt list
====> Social Chair - Hunter Jarrell
====> External Relations - Jing
====> Secretary - Dylan
====> Server Admin - open 

?govt social chair
====> %user% is our current Social Chair!
====> The social chair does a thing.

?govt admin auto
====> The seat positions have been updated since the last election.

?govt admin set server_admin <name/id>
====> %user% has been set as the new Server Admin.

Descriptions attached to each of the seats in a subcommand would be useful as well.
Also, keep note of which command outputs should be sent into more private channels vs. public channels. We want to make sure that we keep internal information (such as who has been reappointed to a position or moved from a position) quiet and in officer channels.

**Comment by hjarrell** [comment]
Closed by #49
