### ISSUE TITLE
Add a !clear [int] command

### ISSUE THREAD

**Issue by hjarrell** [ufosc/albot-and-albota#48]
Add a command to clear messages in a channel. You can use the history function: https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.history and then delete messages here: https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.delete_messages . NOTE: The max amount of messages you can use with delete_messages is 100. So you could either limit the command to 100 or you could limit 100 subtract the counter and keep looping.

**Comment by rennemannd** [comment]
I'm going to take a look at this and see what I can do!
