### ISSUE TITLE
Add logging to bot

### ISSUE THREAD

**Issue by hjarrell** [ufosc/albot-and-albota#6]
Have a log of commands that users use/try to use and what the bot did as output. This might be implemented using the normal python Logging library.

**Comment by JING1201** [comment]
I'm not very familiar with the logging library, where does the output goto?

**Comment by hjarrell** [comment]
It goes to standard output but using the basic config you pass a file name and it logs to a file. 

https://docs.python.org/3/howto/logging.html

**Comment by JING1201** [comment]
For this issue, are you referring to the bot writing to a log file on the server?

**Comment by hjarrell** [comment]
Yes just a little audit log of the errors and commands that are used. That way if someone tries to crash the bot or something we can find it. Or if there is a bug we need to track down.

**Comment by hjarrell** [comment]
Here's a guide from the official docs: https://discordpy.readthedocs.io/en/latest/logging.html

**Comment by logandgsmith** [comment]
@hjarrell Do you still think this would be a good feature to add? I'm wondering how often we'd really check the logs.

**Comment by hjarrell** [comment]
It isn't really something to check all the time just a log file so that we can debug errors.

**Comment by logandgsmith** [comment]
@hjarrell completed this in #100. On to the next one!
