### ISSUE TITLE
Add a database connection and interaction through commands

### ISSUE THREAD

**Issue by hjarrell** [ufosc/albot-and-albota#7]
Add a way for the bot to connect to a database. It would be great to abstract away the implementation of which database the bot is connecting to (sqlite, postgresql, mysql, ...) maybe using something like https://github.com/web2py/pydal .

One easy command could probably be something like:
`!executesql "raw sql goes here"`
but just for admins to run.

**Comment by alexandershuping** [comment]
PyDAL is having issues on my machine. Testing the sample code from the repo works fine - 
```python
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydal import DAL, Field
>>> db = DAL('sqlite://storage.db')
>>> db.define_table('thing', Field('name'))
<Table thing (id, name)>
>>> db.thing.insert(name='Chair')
1
>>> query = db.thing.name.startswith('C')
>>> rows = db(query).select()
>>> print(rows[0].name)
Chair
>>> db.commit()
```
But it doesn't seem to be reading tables from files properly.
```python
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydal import DAL, Field
>>> db = DAL('sqlite://storage.db')
>>> query = db.thing.name.startswith('C')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pydal/base.py", line 669, in __getattr__
    return BasicStorage.__getattribute__(self, key)
AttributeError: 'DAL' object has no attribute 'thing'
```

@hjarrell, could you or someone else test this and see if you can reproduce?

**Comment by hjarrell** [comment]
I'm getting the same error. I tried playing around with a couple parameters when it loads the db and still didn't get it to work.
