### ISSUE TITLE
Alert Officers about Credit Left in Server Fund

### ISSUE THREAD

**Issue by logandgsmith** [ufosc/albot-and-albota#76]
It would be good if the bot alerted us of low server funds either monthly or with a command. We'd need to have the bot pull information from our DigitalOcean account, which our Server Admin has access to.

**Comment by swiftlee** [comment]
I can take a look at this. I can link in with DigitalOcean or authenticate into DigitalOcean and scrape page that has the necessary data.

**Comment by logandgsmith** [comment]
Thanks! Let me know if you need any help!

**Comment by hjarrell** [comment]
Closing this as the DigitalOcean API currently doesn't support this lookup: https://developers.digitalocean.com/documentation/v2/#billing-history
