### ISSUE TITLE
Good Bot Bad Bot tally

### ISSUE THREAD

**Issue by asantacoloma24** [ufosc/albot-and-albota#8]
Recognize when users comment on whether the bot is doing a function well or poorly

**Comment by hjarrell** [comment]
@asantacoloma24 Hows this going? Need any help?

**Comment by logandgsmith** [comment]
It'd be cool to tie this to the website once it's up and running!

**Comment by logandgsmith** [comment]
Completed in #95. Closing issue and on to the next one! Nice work everyone!
