### ISSUE TITLE
Make a !leave Command

### ISSUE THREAD

**Issue by logandgsmith** [ufosc/albot-and-albota#92]
We have a !join command to join new projects, but how do you leave? Currently we have to manually remove members from project teams, and they can be a bit of a hassle. That's where you come in! Using the code for the !join command and the [discord.py docs](https://discordpy.readthedocs.io/en/latest/), please help us make a leave command to remove the role of the specified project. 

Another thing to look at is removing all project roles when joining the alumni role. The alumni can definitely still rejoin projects, but it might save them a bit of hassle by removing roles for them.

Good Luck!

**Comment by udoedo** [comment]
Hi, can I work on this ?

**Comment by logandgsmith** [comment]
Absolutely! You can also join our org's Discord (on our page) if you need any help.

**Comment by logandgsmith** [comment]
Completed by @udoedo in #94. Thanks again!
